sudo: false
language: node_js
node_js:
  - 5.10.1

script:
  - npm run build
  - npm test

notifications:
  slack:
    - secure: "AsULupo0aeJ0eEKf//TLouzS6wz6syxxec51lmKlU7yjcPb5pPDdPd0UysiXSmSKVHwTSkTBk5xmXxWur7/LFvvo3PdZMchXJzr1rda7ATh3koYXTiGUjIub/aPaqgfIEo9hE1jDzQ/RdlblUPZXLNps58oork4BMefMi2kW7M46z38gV7FfX6xoG0gCLiZabPlgi0AZrPmhf4j+jLW2vhBDwWs07C3+dVQhU3f3lThA3QUk/u5J5yZUgP3W/fiV6P6Aht4OMmn5EgKXr3ly7qtUEKAzbvnxUqjaup6nh49e9OJlJnYiEswjWPNVtNohV2PZdTmSh+MhGV6Ht8oWnR+C1kNcriKD/3MggCf0KQETIyCfIYIhd5ht2tJqMOfGEdehSRg6bI6pxFfLVUWvebjrSCQWD5iXAvRmGRuiHTo9TWTgpyvqsnwjNrP/DB30lsxV+GM+RhTFTQdDQbzd57GcZdcUB/26MgTLfc/6CXt1C5Dsz9T2HspxgZHgTV8R+4gVc4lfgrvQKHKUgr7v1S6D2q8GkSGC9mrVW4BbeBkQ8NBDlmHK3HP33x5WB67rQNJnpDgFQ1R7CjwKSFWrMvOU+Z2brxleCC/XEdLHoRkrVRvPPI92WMn06cNJo+XvIGjB329yWFJBGLG8tAK1PTGVbryPJcQ2gLQgeo/28XY="
