sudo: false
language: node_js
node_js:
  - 5.10.1

script:
  - npm run build
  - npm test

notifications:
  slack:
    - secure: "Y1Ur9olGD+3bYwZlk3wYXxdyUSjCg7TXhWxpopHa7NVH7MoMf3KEO25nucy0L0mXZjCuPIj1gWHClfFRENC+Ztauz133NsQCU1yUOuOTUsMLa40nath+1FMW9K59hW9pX0UdX4GQai16O312Sic/S02uRtLtOCIzX4Ht9COm1VAP9MJsmGJSQv2PmhaX5Q+zFvkNooYG/GR39IqaammPQHyqrjtmA6ih/1aho1+c21dC4N4fxvVAcb48SSUJzDwO82qxmOn7asn61VSp9EyeSnj6VhTDwi5El3wICkJKjNNY9FVSj9y2KqIowsHn0m1qaUH1mk9KIC56g6iQzvZOfEpV4CLyG48JhK9DLPd7FGtaOuinEY1RMSyd97AdY6jFFd9MLCktibQ8teL7A02sgYeJWxeft8RXcK9I9UaO8ZK6SsB4K3CvKThRTaFdz/6e7EsfdyPOjJljZrovVSRpWADHn6LADwgxHQsLZwbq5/Y97tpRQtokZfiA7xVIaiheC9KO/RjSiGs9Be3Y6MFHOht04tCarxOFpce7tPcDM7flLIcUR8//k3c4iOJ0wE4+YBaMvEo/svo/xJBaSTTnXxqyq6aHocqlqBuvHDHzW8GgNHoj4yot8XI8JxyNGnAa1Ap6ps94AM8XRc3Clug7mlYA5bu+3DUcJlYX9ekz4Rk="
